Chrome to electron
Kilian/electron-to-chromium pull request #6
Opened 2017-03-17 12:49 UTC by yavorsky

Add chromiumToElectron method with reversed logic.
For performance and other purposes also added it to build.js for `chrome-versions.js` and `full-chrome-versions.js` builds.

2017-03-17 15:04 UTC, Kilian commented
Nice extension, code looks fine :) Any particular use for this in mind? 

Could you update the README.md with the new functions and lists? The full chrome versions returns an array instead of a string so that would be important to communicate clearly.

2017-03-17 15:15 UTC, yavorsky commented
@Kilian Ah, yes!

2017-03-24 11:24 UTC, Kilian commented
Also needs the description for importing the individual version files. I don't mind doing this but don't know when I'll get around to it. If you beat me to it that would be great ;)

2017-03-26 13:46 UTC, Kilian commented on index.js
> +  chromeVersions: chromeVersions,
please use 'chromium' for consistency

2017-03-26 13:49 UTC, Kilian requested changes
Please use "chromium" instead of "chrome" for consistency, in the property names and filenames.

Please make sure that the new properties and files are added to the readme (with chromium in their names)

2017-03-26 14:35 UTC, Kilian commented
I made the above changes in this branch: https://github.com/Kilian/electron-to-chromium/tree/yavorsky-chrome-to-electron 

@yavorsky did I miss anything?

2017-03-27 09:41 UTC, yavorsky commented
@Kilian Can you please open PR `yavorsky-chrome-to-electron` to `master` to compare changes, reviews, etc? 🙂

2017-03-27 09:50 UTC, Kilian commented
Closing this to continue in #8.

2017-03-27 09:50 UTC, closed without merging